name: "test"

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Configure committer
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
    - uses: ./
